// GENERATED by scripts/generate-officer-credentials.js — do not edit by hand.
//
// TEMPORARY. These are real officer credentials in plaintext, compiled
// into the app bundle. A bundle is not a secret: anyone with the .ipa or
// .apk can read every password here. This exists only so the app can be
// used before the backend has the accounts.
//
// Sign-in falls back to this table ONLY when the server cannot be
// reached, so it retires itself the moment the real API answers.
//
// TO REMOVE: delete this file and the offline-auth block in lib/auth.ts,
// then rotate every password below.
//
// Generated 2026-09-20T16:42:45.251Z

export interface DevAccount {
  username: string;
  password: string;
  id: string;
  name: string;
  role: string;
  studentNumber: string;
  course: string;
  yearLevel: string;
}

/**
 * Built-in sign-in is on in development, and off in a release build
 * unless EXPO_PUBLIC_OFFLINE_AUTH=1 is set at build time. That default
 * is what stops these credentials reaching the App Store by accident.
 */
export const OFFLINE_AUTH_ENABLED: boolean =
  __DEV__ || process.env.EXPO_PUBLIC_OFFLINE_AUTH === "1";

export const DEV_ACCOUNTS: DevAccount[] = [
  {"username":"jmonzor","password":"xT4FhL6x","id":"local-S2024101547","name":"Jessam Mae Dumpa Monzor","role":"officer","studentNumber":"S2024101547","course":"BSIT","yearLevel":"3rd Year"},
  {"username":"jcarandang","password":"cp27Sn6B","id":"local-S2024100023","name":"Jamie Pearl Unera Carandang","role":"officer","studentNumber":"S2024100023","course":"BSCS","yearLevel":"3rd Year"},
  {"username":"mcamat","password":"h3qPNMch","id":"local-S2025100092","name":"Mhica Claire Gutierrez Camat","role":"officer","studentNumber":"S2025100092","course":"BSEMC","yearLevel":"2nd Year"},
  {"username":"plat","password":"A6cZ24CJ","id":"local-S2024100805","name":"Pauline Mae Redor Lat","role":"officer","studentNumber":"S2024100805","course":"BSIT","yearLevel":"3rd Year"},
  {"username":"lpoblete","password":"7nWzeVkR","id":"local-S2025100781","name":"Lana Clare Dela Cruz Poblete","role":"officer","studentNumber":"S2025100781","course":"BSIT","yearLevel":"2nd Year"},
  {"username":"edictado","password":"vm2Tym2J","id":"local-S2025101493","name":"Earl Joseph Cartabio Dictado","role":"officer","studentNumber":"S2025101493","course":"BSIT","yearLevel":"2nd Year"},
  {"username":"gzita","password":"5aLrtf8i","id":"local-S2025101510","name":"Gabriel Balazon Zita","role":"officer","studentNumber":"S2025101510","course":"BSIT","yearLevel":"2nd Year"},
  {"username":"kcabanglan","password":"zq7tqrST","id":"local-S2024100040","name":"Kyle Angel Tajan Cabanglan","role":"officer","studentNumber":"S2024100040","course":"BSIT","yearLevel":"3rd Year"},
  {"username":"amalijan","password":"qWncw5zZ","id":"local-S2025100267","name":"Ashley Nicole Maman Malijan","role":"officer","studentNumber":"S2025100267","course":"BSEMC","yearLevel":"2nd Year"},
  {"username":"nmojares","password":"r35TbC8D","id":"local-S2026101405","name":"Niña Rose Desingaño Mojares","role":"officer","studentNumber":"S2026101405","course":"BSIT","yearLevel":"1st Year"},
  {"username":"jalvarico","password":"Ktmyxd9i","id":"local-S2025101338","name":"John Kienle Hernandez Alvarico","role":"officer","studentNumber":"S2025101338","course":"BSIT","yearLevel":"2nd Year"},
  {"username":"ccamartin","password":"kDeMmMd5","id":"local-S2025102311","name":"Christian Guantes Camartin","role":"officer","studentNumber":"S2025102311","course":"BSCS","yearLevel":"2nd Year"},
  {"username":"mperez","password":"W4hFJmZB","id":"local-S2023100682","name":"Melanie Almero Perez","role":"officer","studentNumber":"S2023100682","course":"BSIT","yearLevel":"4th Year"},
  {"username":"vpunzalan","password":"6Zvnb5Kv","id":"local-S2023101428","name":"Voltaire Jan Otian Punzalan","role":"officer","studentNumber":"S2023101428","course":"BSCS","yearLevel":"4th Year"},
  {"username":"jdechavez","password":"Gx8u3QtU","id":"local-S2023100104","name":"Jann Railey Aquino De Chavez","role":"officer","studentNumber":"S2023100104","course":"BSEMC","yearLevel":"4th Year"},
  {"username":"ngumila","password":"LiMNed6z","id":"local-S2024101442","name":"Naika Ishi Dela Cruz Gumila","role":"officer","studentNumber":"S2024101442","course":"BSIT","yearLevel":"3rd Year"},
  {"username":"jplatero","password":"r82WsUJT","id":"local-S2024101507","name":"Jose Eugenio Pawig Platero","role":"officer","studentNumber":"S2024101507","course":"BSIT","yearLevel":"3rd Year"},
  {"username":"nmorte","password":"iEaCnFQf","id":"local-S2024100024","name":"Neil Allen Panalangin Morte","role":"officer","studentNumber":"S2024100024","course":"BSCS","yearLevel":"3rd Year"},
  {"username":"cmanalo","password":"JAwjj2t4","id":"local-S2024100940","name":"Clarence Bravante Manalo","role":"officer","studentNumber":"S2024100940","course":"BSEMC","yearLevel":"3rd Year"},
  {"username":"pcacao","password":"2FKNj94H","id":"local-S2025100094","name":"Prince Jemille Fajardo Cacao","role":"officer","studentNumber":"S2025100094","course":"BSIT","yearLevel":"2nd Year"},
  {"username":"rformanes","password":"SVT8pvmY","id":"local-S2025101623","name":"Renzo Perea Formanes","role":"officer","studentNumber":"S2025101623","course":"BSIT","yearLevel":"2nd Year"},
  {"username":"dgutierrez","password":"j7ww95My","id":"local-S2025100708","name":"Dominic Guerrero Gutierrez","role":"officer","studentNumber":"S2025100708","course":"BSCS","yearLevel":"2nd Year"},
  {"username":"celcarte","password":"sbC4ZEaJ","id":"local-S2025102276","name":"Cristine Mae San Jose Elcarte","role":"officer","studentNumber":"S2025102276","course":"BSEMC","yearLevel":"2nd Year"},
  {"username":"ycarandang","password":"MDXkRDBn","id":"local-S2026101165","name":"Yvonne Althea Maamo Carandang","role":"officer","studentNumber":"S2026101165","course":"BSIT","yearLevel":"1st Year"},
  {"username":"iatienza","password":"EvRWDPru","id":"local-S2026100314","name":"Iya Dianne Atienza","role":"officer","studentNumber":"S2026100314","course":"BSIT","yearLevel":"1st Year"},
  {"username":"ksantiago","password":"ALrXazp7","id":"local-S2026100474","name":"Karyl Fay Valencia Santiago","role":"officer","studentNumber":"S2026100474","course":"BSCS","yearLevel":"1st Year"},
  {"username":"ldegarejo","password":"Z5XcDU6V","id":"local-S2026100628","name":"Lawrence Andrei Acasio De Garejo","role":"officer","studentNumber":"S2026100628","course":"BSEMC","yearLevel":"1st Year"},
];

/** Case-insensitive on the username, exact on the password. */
export function findDevAccount(username: string, password: string): DevAccount | null {
  const u = (username || "").trim().toLowerCase();
  return (
    DEV_ACCOUNTS.find((a) => a.username.toLowerCase() === u && a.password === password) ?? null
  );
}
